### ISSUE TITLE
Hypothesis environment gets broken through package hyphenat 

### ISSUE THREAD

**Issue by BaumiCoder** [se2p/se2thesis#19]
The `hyp` environment from se2thesis gets broken if the package [hyphenat](https://ctan.org/pkg/hyphenat) is loaded. In the example document it looks like this with the `\usepackage{hyphenat}` in the preamble (not mater in which order):
![screenshot from example document](https://github.com/user-attachments/assets/9a3dfdba-90dc-409c-af4c-1318715ab44e)

I use the `hyphenat` package for the `\hyp{}` macro for a hyphen `-`. This allows LaTeX to make automatic hyphenation in words with a hyphen also on other positions (see this [blog post](https://blog.hartwork.org/posts/hypthenation-in-latex-why-it-kills-how-to-survive/)).

My versions:

- Document Class: se2thesis 2024-07-23 v4.3.0 A thesis class for the Chair of Software Engineering II
- hyphenat.sty    2009/09/02 v2.3c hyphenation utilities

**Comment by BaumiCoder** [comment]
Defining a new theorem with another key than `hyp` for the hypothesis is a workaround for the problem. 
```tex
\newtheorem{hypothesis}
% ...
\begin{document}
% ...
\begin{hypothesis}\label{hyp:1}
  We hypothesise that the answer to \cref{rq:1} is 42!
\end{hypothesis}
% ...
\end{document}
```
However, such a change for se2thesis itself would not the best idea, because, I think, it would be a breaking change. (Or could `hyp` be an "alias" for `hypothesis` here to support both keys?)

**Comment by stephanlukasczyk** [comment]
Alternative solution (because `hyphenat` had its last release 20 years ago and I am not sure whether there are any issues with that package; plus I do not want to introduce yet another breaking change now in `se2thesis`): why not use the shorthands provided by [`babel`](https://ctan.org/pkg/babel)—which should be loaded by default (or its alternative `polyglossia`), see e.g. https://tex.stackexchange.com/a/298844/14622

*Edit:* I've added explicit documentation on this in 1f041cb621afbd54250bd8f189c9c3c4af9aa465
