### ISSUE TITLE
Bachelor-thesis/ Master-thesis translation values

### ISSUE THREAD

**Issue by timlg07** [se2p/se2thesis#20]
I updated se2thesis to the latest version and the translations for the thesis type do no longer work. Instead of `Master Thesis` or the updated `Master's Thesis`, it just says `Master-thesis`.

Tested with the following minimal example:

```tex
\documentclass[%
chapterprefix=false,%
open=right,%
twoside=true,%
paper=a4,%
thesistype=master,%
UKenglish,%
]{se2thesis}
\listfiles
\usepackage[ngerman,main=UKenglish]{babel}
\usepackage{blindtext}
\usepackage[%
csquotes=true,%
booktabs=true,%
siunitx=true,%
minted=true,%
selnolig=true,%
widowcontrol=false,%
microtype=true,%
biblatex=numeric,%
cleveref=true,%
]{se2packages}

\usepackage{hyperref}

\author{Stephan Lukasczyk}
\title{A Master Thesis Example Document}
\degreeprogramme{Computer Science}
\matrnumber{0815}
\supervisor{Prof.\,Dr.~Max Mustermann}
\external{Prof.~John Doe,~PhD}
\advisor{Marianne Musterfrau}
\department{Faculty of Examples}
\institute{Chair of Example}
\location{Passau}

\begin{document}
	\frontmatter
	\maketitle
\end{document}
```

Result:

![image](https://github.com/user-attachments/assets/02406f76-98be-4500-aac6-070204545f33)

When including `\GetTranslation{Master-thesis}` in the document directly, it also does not get translated, while it works fine for older versions of the se2thesis package.

**Comment by stephanlukasczyk** [comment]
Thanks for the report.  Unfortunately, I cannot reproduce the issue with the MWE you've provided (see atteched screenshot).  The version of `se2thesis` I have here is 4.3.2 from 2024–08–12, which is commit cc8d428be.  Could you please provide me a log file from the `lualatex` (or `pdflatex`) run?

![Screenshot 2024-08-26 at 15 57 01](https://github.com/user-attachments/assets/4596be87-3cdf-432e-ae34-e89721307246)

**Comment by timlg07** [comment]
Thanks for the response, might be just a problem with my setup then.  
I fixed it by simply providing a fallback, e.g. `
\DeclareTranslationFallback{Master-thesis}{Master's Thesis}`.

The log file contains the following warning, which I assumed is the cause of the missing translation:  
`Package translations Warning: no dictionary file 'se2translations-english.trsl' found. on input line 59.`

(I use version 4.3.1 from 2024-08-06, which is the latest version according to MiKTeX)

**Comment by stephanlukasczyk** [comment]
Ah, MikTeX is serving you an old version 🙈 I, unfortunately, cannot say how and whether one can trigger an update—I am uploading new versions of `se2thesis` to [CTAN](https://ctan.org/pkg/se2thesis) from which both MikTeX and TeX Live get their packages.  Since I am only using TeX Live (MikTeX is only running on M$ systems, IIRC, and I have not touched an M$ system for like 10+ years), I cannot help with MikTeX.  However, I do recommend to probably switch to TeX Live because it usually provides CTAN updates within at most two to three days to the users.

What you could try is cloning this repository and install it with `l3build install` to your `$LOCALTEXMF`—if this exists in MikTeX (it does in TeX Live).

The warning from the log file looks like it is the root of the problem, yes.

**Comment by stephanlukasczyk** [comment]
For the sake of completeness, @timlg07 , where you able to update to 4.3.2 and test it again?  If that fixes the issue for you, I'd like to close the issue.

**Comment by timlg07** [comment]
The fix with the translation fallbacks works for now, so I focus on my thesis right now 🙈 But it sounds like a problem with the installation, not with the code itself, so I'm going to close this issue.
