### ISSUE TITLE
Add support for titlecaps

### ISSUE THREAD

**Issue by BaumiCoder** [se2p/se2thesis#9]
The package [titlecaps](https://ctan.org/pkg/titlecaps) can capitalize text for titles. It would be nice to apply this automatically to all titles (chapter, section, ...). I already tired, but it always fails with compiling errors.
1. renewcommand
2. setkomafont or addtokomafont (see `3.6. Text Markup` in the documentation of [scrbase](https://ctan.org/pkg/scrbase))

The titles are mostly written uppercase, but at least in the table of contents the low- / uppercase writing matters.

**Comment by stephanlukasczyk** [comment]
I've created a preliminary implementation in #10 , you might want to try that by cloning the branch, running `l3build install`, and configuring your `TEXMFLOCAL`.

*But:* I am not planning to merge this in the near future because it is simply (a) not feature complete (see PR on details), (b) it feels like a dirty hack, and (c) I strongly believe that capitalisation is some thing one wants to do by hand.

Let me elaborate on the last point: while there are plenty of rules for plenty of style guides there always exist exceptions to the rules that one wants to have for good reasons.  While it still might be possible to automatise all these exceptions, I doubt that it's worth the effort. Especially, since online services for capitalisation are available.  Thus, I let this here if you want to play around with it.  I am happy to accept further contributions to #10 that fix the open problems.  If the open problems are fixed and the PR is tested well, I might merge it at some point and release it.
